# Generated by Django 2.2.6 on 2019-10-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club4u.Category')),
                ('summary', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('poster_img', models.ImageField(blank=True, upload_to='')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_dept', to='club4u.Department')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dept', to='club4u.Department')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_major', to='club4u.Department')),
                ('grade', models.IntegerField(default=1)),
                ('available_semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Somoim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='somoim_author', to='club4u.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='somoim_category', to='club4u.Category')),
                ('summary', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('goalJoiner', models.IntegerField(default=0)),
                ('currentJoiner', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeSomoim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somoim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikesomoim_somoim_id', to='club4u.Somoim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikesomoim_user_id', to='club4u.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikeclub_club_id', to='club4u.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikeclub_user_id', to='club4u.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinSomoim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somoim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userjoinsomoim_somoim_id', to='club4u.Somoim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userjoinsomoim_user_id', to='club4u.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplyClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userapplyclub_club_id', to='club4u.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userapplyclub_user_id', to='club4u.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PreClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preclub_category', to='club4u.Category')),
                ('manager', models.CharField(max_length=64)),
                ('auth_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
