# Generated by Django 2.2.6 on 2019-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('isRegistered', models.BooleanField(default=False)),
            ],
        ),
    ]
