# Generated by Django 2.2.5 on 2019-11-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='somoim',
            name='selected_dept',
        ),
        migrations.RemoveField(
            model_name='somoim',
            name='tags',
        ),
    ]
