# Generated by Django 2.2.6 on 2019-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='poster_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='preclub',
            name='auth_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
