# Generated by Django 2.2.5 on 2019-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somoim',
            name='available_sem',
            field=models.IntegerField(default=0),
        ),
    ]
