# Generated by Django 2.2.6 on 2019-11-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0002_auto_20191101_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
