# Generated by Django 2.2.5 on 2019-11-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0002_auto_20191105_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='somoim',
            name='selected_dept',
            field=models.ManyToManyField(blank=True, related_name='somoim_dept', to='club4u.Department'),
        ),
        migrations.AddField(
            model_name='somoim',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='somoims', to='club4u.Tag'),
        ),
    ]
