# Generated by Django 2.2.6 on 2019-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0002_auto_20191030_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somoim',
            name='goalJoiner',
            field=models.IntegerField(default=0),
        ),
    ]
