# Generated by Django 2.2.5 on 2019-11-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0002_auto_20191101_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjoinsomoim',
            name='somoim',
        ),
        migrations.RemoveField(
            model_name='userjoinsomoim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlikeclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='userlikeclub',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlikesomoim',
            name='somoim',
        ),
        migrations.RemoveField(
            model_name='userlikesomoim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='club',
            name='author',
        ),
        migrations.RemoveField(
            model_name='somoim',
            name='author',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='apply_clubs',
            field=models.ManyToManyField(related_name='appliers', to='club4u.Club'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_somoims',
            field=models.ManyToManyField(related_name='joiners', to='club4u.Somoim'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_clubs',
            field=models.ManyToManyField(related_name='likers', to='club4u.Club'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_somoims',
            field=models.ManyToManyField(related_name='likers', to='club4u.Somoim'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manage_clubs',
            field=models.ManyToManyField(related_name='manager', to='club4u.Club'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manage_somoims',
            field=models.ManyToManyField(related_name='manager', to='club4u.Somoim'),
        ),
        migrations.DeleteModel(
            name='UserApplyClub',
        ),
        migrations.DeleteModel(
            name='UserJoinSomoim',
        ),
        migrations.DeleteModel(
            name='UserLikeClub',
        ),
        migrations.DeleteModel(
            name='UserLikeSomoim',
        ),
    ]
