# Generated by Django 2.2.5 on 2019-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0002_auto_20191106_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manage_clubs',
            field=models.ManyToManyField(blank=True, related_name='managers', to='club4u.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manage_somoims',
            field=models.ManyToManyField(blank=True, related_name='managers', to='club4u.Somoim'),
        ),
    ]
