# Generated by Django 2.2.5 on 2019-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0003_auto_20191106_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='somoim',
            name='currentJoiner',
        ),
        migrations.RemoveField(
            model_name='somoim',
            name='likes',
        ),
    ]
