# Generated by Django 2.2.5 on 2019-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0003_auto_20191104_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apply_clubs',
            field=models.ManyToManyField(null=True, related_name='appliers', to='club4u.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='join_somoims',
            field=models.ManyToManyField(null=True, related_name='joiners', to='club4u.Somoim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='like_clubs',
            field=models.ManyToManyField(null=True, related_name='likers', to='club4u.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='like_somoims',
            field=models.ManyToManyField(null=True, related_name='likers', to='club4u.Somoim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manage_clubs',
            field=models.ManyToManyField(null=True, related_name='manager', to='club4u.Club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manage_somoims',
            field=models.ManyToManyField(null=True, related_name='manager', to='club4u.Somoim'),
        ),
    ]
