# Generated by Django 2.2.5 on 2019-11-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0006_application_fileform_imageform_longtextform_multichoiceform_shorttextform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='club4u.UserProfile'),
        ),
    ]
