# Generated by Django 2.2.5 on 2019-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0007_choice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='longtextform',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shorttextform',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
