# Generated by Django 2.2.5 on 2019-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0007_auto_20191113_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileform',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageform',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
