# Generated by Django 2.2.5 on 2019-11-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0009_choice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='club4u.Club'),
        ),
    ]
