# Generated by Django 2.2.5 on 2019-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0010_auto_20191118_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='suggested',
            field=models.IntegerField(default=0),
        ),
    ]
