# Generated by Django 2.2.5 on 2019-11-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0011_auto_20191124_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='selected',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='suggested',
            field=models.IntegerField(default=1),
        ),
    ]
