# Generated by Django 2.2.5 on 2019-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0012_auto_20191124_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somoim',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
