# Generated by Django 2.2.5 on 2019-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0013_auto_20191208_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='somoim',
            name='member',
            field=models.IntegerField(default=0),
        ),
    ]
