# Generated by Django 2.2.8 on 2019-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club4u', '0014_auto_20191208_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubposter',
            name='point0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubposter',
            name='point1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubposter',
            name='point2',
            field=models.IntegerField(default=0),
        ),
    ]
