matrix:
  include:
    - language:
        - python
      cache:
      pip: true
      node_js:
        - "10"
      python:
        - "3.6.8"
      dist: xenial
      services:
        - mysql
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "J60TSPUi8FY37NcYj7T/V+t7dhPN92qjPIb9TE44YzeBcV8Gea3v8TjdqEARowyy15uOLQHsivrV/6WRiVLyF4J0en8KwOg5CrxT1IR5icNRU06bSoCLBe84+33YFHfyIs53CcE128UEVNYCrv2NqTyvkI0CVyIFC2OJCQ6B56AGvLJCpInYGlGJXVJReqROgUAm0q5LH6iy4s2TDbfFdUut5ITlf6mPoMm51WikwppNIACgIveH+l0gKbAfx+wYCW6aST/yEplsXzF61RmygsNvfjTXh642Od9erlNFJUwU0twh+N+O1HkZjXz2PVYnKDLgEk8WtyxtAm03qySBIwSDZDtDfEUZFGUZz+dN9uVnsUL/6ob5laKU/d3kYSOkaVu32wuIcMfa4qYCGNevbr/a9MimAmwaW0T/rBS/TQoILNt7s6MROuQEaAWOe6SxuNLKzYX5sqCibcnpLVQedEE+DDoQKa5YdeQlfY/W/eBpa1Hx7Vu0TtfVv0TVxmzogfo/hVqAR1W25H/eGBCUlzXl5T0ZarHZySgCXO0+zV7WmhYYOFXcbPzP1hjwbgYxfzdhwR7E6Kj642MGTWULn7/k6uGJqjWLWqy3vXpRMfflmTrC2MZ+IlYj5rqW3rE9MO5IXCMgyGG6qsU6weMHrwpBcekWJM4ywNPW2NNWeWM="
      before_install:
        - mysql -e "CREATE DATABASE club4u;"
      install:
        - cd frontend
        - npm install
        - npm install coveralls
        - gem install coveralls-lcov
        - cd ..
        - cd backend
        - pip install -r requirements.txt
        - pip install coveralls
        - cd ..
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - cd ..
        - cd backend
        - pylint --load-plugins pylint_django */models.py */views.py */test/*.py --disable='C0103, R1705, C0301, R0904, R0801, C0412, C0114, C0115, C0116, W0511, C0330, C0303, W0614, W0401, R1721, R0912, R0914, R0915, C0200, W0621'
        - coverage run --branch --source='./club4u' manage.py test
        - coverage report --fail-under=90
        - coverage xml
        - cd ..
        - sonar-scanner
      after_success:
        - cd frontend
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ..
        - cd backend
        - coveralls --merge=../frontend/coverage.json
        - cd ..
      after_failure:
        - cd frontend
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ..
        - cd backend
        - coveralls --merge=../frontend/coverage.json
        - cd ..
