export const GET_CLUB_LIST = "GET_CLUB_LIST";
export const GET_CLUB_BY_ID = "GET_CLUB_BY_ID";
export const POST_CLUB = "POST_CLUB";
export const INCREASE_LIKES_OF_CLUB = "INCREASE_LIKES_OF_CLUB";

export const GET_SOMOIM_LIST = "GET_SOMOIM_LIST";
export const GET_SOMOIM_BY_ID = "GET_SOMOIM_BY_ID";
export const POST_SOMOIM = "POST_SOMOIM";
export const INCREASE_LIKES_OF_SOMOIM = "INCREASE_LIKES_OF_SOMOIM";
export const INCREASE_NUM_OF_CURRENT_JOINER = "INCREASE_NUM_OF_CURRENT_JOINER";

export const GET_USER_LIST = "GET_USER_LIST";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";
export const GET_LOGIN_INFO = "GET_LOGIN_INFO";

export const PUT_USER_INFORMATION = "PUT_USER_INFORMATION";

export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_TAG_LIST = "GET_TAG_LIST";

export const GET_DEPT_LIST = "GET_DEPT_LIST";
export const GET_MAJOR_LIST = "GET_MAJOR_LIST";

export const GET_MANAGING_CLUBS = "GET_MANAGING_CLUBS";
export const GET_LIKED_CLUBS = "GET_LIKED_CLUBS";
export const GET_APPLIED_CLUBS = "GET_APPLIED_CLUBS";
export const GET_RECOMMENDED_CLUBS = "GET_RECOMMENDED_CLUBS";

export const GET_MANAGING_SOMOIMS = "GET_MANAGING_SOMOIMS";
export const GET_LIKED_SOMOIMS = "GET_LIKED_SOMOIMS";
export const GET_JOINED_SOMOIMS = "GET_JOINED_SOMOIMS";
export const GET_RECOMMENDED_SOMOIMS = "GET_RECOMMENDED_SOMOIMS";

export const ADD_LIKED_CLUB = "ADD_LIKED_CLUB";
export const ADD_LIKED_SOMOIM = "ADD_LIKED_SOMOIM";

export const ADD_APPLIED_CLUB = "ADD_APPLIED_CLUB";
export const ADD_JOINED_SOMOIM = "ADD_JOINED_SOMOIM";
export const POST_PRECLUB = "POST_PRECLUB";

export const ADD_MANAGING_SOMOIM = "ADD_MANAGING_SOMOIM";
